spring.application.name=AiLanguageApp

server.port=2020

spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

openai.api.key=${OPENAI_API_KEY}
openai.model=gpt-5-mini
